# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

env:
    - RGL_USE_NULL=TRUE

r_check_args: --as-cran

r:
    - 3.3
    - oldrel
    - release
    - devel

after_failure:
      - cat "${RCHECK_DIR}/00install.out"

after_success:
      - cat "${RCHECK_DIR}/00install.out"
